apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aob6qrrzm-nodejs
  janus-idp.io/tekton: aob6qrrzm-nodejs
  backstage.io/kubernetes-id: aob6qrrzm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aob6qrrzm-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
