apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: aob6qrrzm-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:aa7ab2433f4395f91a3dd45145dd3add8ef5c4a6@sha256:6a5698090bd456da96c1042b4bea5ff9173778a88270241a78d7414488dcd69e
          name: container-image
